#include <iostream>

using namespace std;

#include <ctime>
// Eigen core 
#include <Eigen/Core>
// Algebraic operation (inverse, feature value, etc.) of dense matrix
#include <Eigen/Dense>

using namespace Eigen;

#define MATRIX_SIZE 50

/****************************
* This program demonstrates basic use of Eigen
****************************/

int main(int argc, char **argv) {
  // Eigen All vector and matrices areEigen::MatrixIt is a template class.The first three parameters: data type, line, column
  // Declare one 2*3 float matrix
  Matrix<float, 2, 3> matrix_23;

  // Simultaneously,Eigen provides many built in types, the following is Eigen::Matrix
  // E.g Vector3d is essentially Eigen::Matrix<double, 3, 1> a 3D vector
  Vector3d v_3d;
  // This is the same
  Matrix<float, 3, 1> vd_3d;

  // Matrix3d Essentially is Eigen::Matrix<double, 3, 3>
  Matrix3d matrix_33 = Matrix3d::Zero(); //Initialization is zero
  // If you are not sure about the size of the matrix, you can use a dynamically sized matrix.
  Matrix<double, Dynamic, Dynamic> matrix_dynamic;
  // Simpler
  MatrixXd matrix_x;
  // There are still a lot of more types that we do not list them.

  // Below is Eigen Array operation
  // Enter data (initialization)
  matrix_23 << 1, 2, 3, 4, 5, 6;
  // Output
  cout << "matrix 2x3 from 1 to 6: \n" << matrix_23 << endl;

  // use () to access the elements in the matrix
  cout << "print matrix 2x3: " << endl;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 3; j++) cout << matrix_23(i, j) << "\t";
    cout << endl;
  }

  // Matrix and vector multiplication (actually still matrix and matrix)
  v_3d << 3, 2, 1;
  vd_3d << 4, 5, 6;

  // With Eigen You can't mix two different types of matrices, the following is wrong
  // Matrix<double, 2, 1> result_wrong_type = matrix_23 * v_3d;
  // Explicit conversion
  Matrix<double, 2, 1> result = matrix_23.cast<double>() * v_3d;
  cout << "[1,2,3;4,5,6]*[3,2,1]=" << result.transpose() << endl;

  Matrix<float, 2, 1> result2 = matrix_23 * vd_3d;
  cout << "[1,2,3;4,5,6]*[4,5,6]: " << result2.transpose() << endl;

  // Similarly, you can’t make a mistake about the dimensions of the matrix
  // Uncomment the following line and see what error Eigen will report?
  // Eigen::Matrix<double, 2, 3> result_wrong_dimension = matrix_23.cast<double>() * v_3d;

  // Some matrices
  // The four operations will not be demonstrated, directly+-*/I.e.
  matrix_33 = Matrix3d::Random();      // Random number matrix
  cout << "random matrix: \n" << matrix_33 << endl;
  cout << "transpose: \n" << matrix_33.transpose() << endl;      // Transpose
  cout << "sum: " << matrix_33.sum() << endl;            // Each element and
  cout << "trace: " << matrix_33.trace() << endl;          // trace
  cout << "times 10: \n" << 10 * matrix_33 << endl;               // Number
  cout << "inverse: \n" << matrix_33.inverse() << endl;        // Reverse
  cout << "det: " << matrix_33.determinant() << endl;    // Row

  // Eigenvalues
  // Real symmetric matrix can guarantee the success of diagonalization
  SelfAdjointEigenSolver<Matrix3d> eigen_solver(matrix_33.transpose() * matrix_33);
  cout << "Eigen values = \n" << eigen_solver.eigenvalues() << endl;
  cout << "Eigen vectors = \n" << eigen_solver.eigenvectors() << endl;

  // Solving equations
  // We solve matrix_NN * x = v_Nd equation
  // N The size is defined in front of the macro, it is generated by the random number
  // The direct inversion is naturally the most direct, but the inversion calculation is large

  Matrix<double, MATRIX_SIZE, MATRIX_SIZE> matrix_NN
      = MatrixXd::Random(MATRIX_SIZE, MATRIX_SIZE);
  matrix_NN = matrix_NN * matrix_NN.transpose();  // Guaranteed semi-definite
  Matrix<double, MATRIX_SIZE, 1> v_Nd = MatrixXd::Random(MATRIX_SIZE, 1);

  clock_t time_stt = clock(); // Timing
  // Direct inverse
  Matrix<double, MATRIX_SIZE, 1> x = matrix_NN.inverse() * v_Nd;
  cout << "time of normal inverse is "
       << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << endl;
  cout << "x = " << x.transpose() << endl;

  // Usually use matrix factorization to find, such as QR factorization, which will be much faster
  time_stt = clock();
  x = matrix_NN.colPivHouseholderQr().solve(v_Nd);
  cout << "time of Qr decomposition is "
       << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << endl;
  cout << "x = " << x.transpose() << endl;

  // For positive definite matrices, you can also use cholesky decomposition to solve the equation
  time_stt = clock();
  x = matrix_NN.ldlt().solve(v_Nd);
  cout << "time of ldlt decomposition is "
       << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << endl;
  cout << "x = " << x.transpose() << endl;

  return 0;
}